# Redirect API requests to the backend
[[redirects]]
from = "/api/*"
to = "https://artgallery-backend-production.up.railway.app/api/:splat"
status = 200

# SPA Routing (catch-all route)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Remove custom MIME type headers (Netlify sets them automatically)
