[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Netlify proxy to avoid CORS issues during development
[[redirects]]
from = "/api/*"
to = "https://artgallery-backend-production.up.railway.app/api/:splat"
status = 200
force = true
